Update Dockerfile
adding missing transformers and diffusers pinned versions

without these, you get the error:
ImportError: cannot import name 'CLIPVisionModelWithProjection' from 'transformers' (D:\WarpFusion\0.24.16\env\lib\site-packages\transformers_init_.py)